In [2]:
import numpy as np

In [4]:

# Tamanho do dataset
n = 200
rng = np.random.default_rng(42)

# Features
x1 = rng.normal(0, 1, n)
x2 = rng.uniform(-2, 3, n)

# Target: y = 4*x1 - 2*x2 + ruído
noise = rng.normal(0, 0.5, n)
y = 4*x1 - 2*x2 + noise

# Empilha em formato (n, 3)
dataset = np.column_stack((x1, x2, y))

print(dataset[:5])
# np.savetxt("dataset_regressao.csv", dataset, delimiter=",")


[[ 0.30471708 -1.93031856  3.92445372]
 [-1.03998411 -0.85171985 -2.42931993]
 [ 0.7504512  -1.34088891  5.44769459]
 [ 0.94056472  1.38829337  1.21536502]
 [-1.95103519 -1.39083748 -4.67148899]]
